### GET /api/split-groups
GET {{appAddress}}/api/split-groups
Authorization: Bearer {{auth_token}}


### GET /api/split-groups/{groupId}
GET {{appAddress}}/api/split-groups/1
Authorization: Bearer {{auth_token}}


### POST /api/split-groups
POST {{appAddress}}/api/split-groups
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "title": "Talking about everything",
  "description": "Let's grab a coffee and talking about anything we want"
}

### PATCH /api/split-groups/{groupId}
PATCH {{appAddress}}/api/split-groups/1
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "title": "Daily",
  "description": "Daily split-group"
}


### DELETE /api/split-groups/{groupId}
DELETE {{appAddress}}/api/split-groups/1
Authorization: Bearer {{auth_token}}


### GET /api/split-groups/{groupId}/users
GET {{appAddress}}/api/split-groups/1/users
Authorization: Bearer {{auth_token}}


### POST /api/split-groups/{groupId}/users/{login}
POST {{appAddress}}/api/split-groups/1/users/admin
Authorization: Bearer {{auth_token}}


### DELETE /api/split-groups/{groupId}/users/{login}
DELETE {{appAddress}}/api/split-groups/1/users/admin
Authorization: Bearer {{auth_token}}

