### GET /api/users
GET {{appAddress}}/api/users
Authorization: Bearer {{auth_token}}


### GET /api/users
GET {{appAddress}}/api/users?sortBy=login&sortOrder=DESC
Authorization: Bearer {{auth_token}}


### GET /api/users
GET {{appAddress}}/api/users?key=a
Authorization: Bearer {{auth_token}}


### GET /api/users/{login}
GET {{appAddress}}/api/users/admin
Authorization: Bearer {{auth_token}}


### POST /api/users
POST {{appAddress}}/api/users
Content-Type: application/json

{
  "login": "admin",
  "password": "password"
}


### DELETE /api/users/{login}
DELETE {{appAddress}}/api/users/admin
Authorization: Bearer {{auth_token}}
